services:
  consul-server:
    image: hashicorp/consul:latest
    tty: true
    container_name: consul-server
    ports:
      - "8500:8500"
    volumes:
      - ./consul/consul-config:/consul/config
    command: "agent -server -bootstrap-expect=1 -node=server1 -ui -client=0.0.0.0"
    networks:
      - app-network

  redis-db:
    image: redis:7-alpine
    container_name: redis-db
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: always

  url-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - CONSUL_HOST=consul-server
      - CONSUL_PORT=8500
    depends_on:
      - consul-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
